apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
    component: web
  name: web-server
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: kube_nginx
        imagePullPolicy: IfNotPresent
        name: test
        ports:
        - containerPort: 80
---
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service
    spec:
      type: LoadBalancer
      selector:
        app: webserver
      ports:
        - port: 80
          targetPort: 80
